# Generated by Django 5.1.7 on 2025-04-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_options_alter_member_fee_package'),
        ('payments', '0002_bill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterField(
            model_name='member',
            name='fee_package',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='payments.feepackage'),
            preserve_default=False,
        ),
    ]
